name: Build
on:
    push:
        branches:
         - "main"
    pull_request:
        branches:
            - "main"
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Install 7zip (I use this for the easy ignorefile integration)
              run: sudo apt-get install p7zip-full
            - name: Run a multi-line script
              run: 7z a dist/${{ github.ref }}.zip . -xr@.buildignore
            - name: Upload archive to artifacts
              uses: actions/upload-artifact@v3
              with:
                  name: dist-zip
                  path: |
                      dist/${{ github.ref }}.zip
